package lotto.model;
// Generated Dec 5, 2009 7:37:40 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * AdminInfo generated by hbm2java
 */
public class AdminInfo  implements java.io.Serializable {


     private Integer adminId;
     private MailingAddress mailingAddress;
     private String username;
     private String password;
     private short active;
     private String name;
     private String email;
     private Set lotteryEvents = new HashSet(0);

    public AdminInfo() {
    }

	
    public AdminInfo(String username, String password, short active, String name, String email) {
        this.username = username;
        this.password = password;
        this.active = active;
        this.name = name;
        this.email = email;
    }
    public AdminInfo(MailingAddress mailingAddress, String username, String password, short active, String name, String email, Set lotteryEvents) {
       this.mailingAddress = mailingAddress;
       this.username = username;
       this.password = password;
       this.active = active;
       this.name = name;
       this.email = email;
       this.lotteryEvents = lotteryEvents;
    }
   
    public Integer getAdminId() {
        return this.adminId;
    }
    
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }
    public MailingAddress getMailingAddress() {
        return this.mailingAddress;
    }
    
    public void setMailingAddress(MailingAddress mailingAddress) {
        this.mailingAddress = mailingAddress;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public short getActive() {
        return this.active;
    }
    
    public void setActive(short active) {
        this.active = active;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getLotteryEvents() {
        return this.lotteryEvents;
    }
    
    public void setLotteryEvents(Set lotteryEvents) {
        this.lotteryEvents = lotteryEvents;
    }
    public void addLotteryEvent(LotteryEvent lotteryEvent) {
        lotteryEvent.setAdminInfo(this);
        lotteryEvents.add(lotteryEvent);
    }



}


