package lotto.model;
// Generated Dec 5, 2009 7:37:40 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LotteryEvent generated by hbm2java
 */
public class LotteryEvent  implements java.io.Serializable {


     private Integer lotteryId;
     private VenueInfo venueInfo;
     private AdminInfo adminInfo;
     private String displayName;
     private Date startTime;
     private Date endTime;
     private Date registerStartTime;
     private Date distributionTime;
     private Date claimEndTime;
     private Date cancelEndTime;
     private Date saleEndTime;
     private Set studentGroups = new HashSet(0);
     private Set lotterySeats = new HashSet(0);
     private Set lotteryRegistrations = new HashSet(0);

    public LotteryEvent() {
    }

	
    public LotteryEvent(VenueInfo venueInfo, AdminInfo adminInfo, String displayName, Date startTime, Date endTime, Date registerStartTime, Date distributionTime, Date claimEndTime, Date cancelEndTime, Date saleEndTime) {
        this.venueInfo = venueInfo;
        this.adminInfo = adminInfo;
        this.displayName = displayName;
        this.startTime = startTime;
        this.endTime = endTime;
        this.registerStartTime = registerStartTime;
        this.distributionTime = distributionTime;
        this.claimEndTime = claimEndTime;
        this.cancelEndTime = cancelEndTime;
        this.saleEndTime = saleEndTime;
    }
    public LotteryEvent(VenueInfo venueInfo, AdminInfo adminInfo, String displayName, Date startTime, Date endTime, Date registerStartTime, Date distributionTime, Date claimEndTime, Date cancelEndTime, Date saleEndTime, Set studentGroups, Set lotterySeats, Set lotteryRegistrations) {
       this.venueInfo = venueInfo;
       this.adminInfo = adminInfo;
       this.displayName = displayName;
       this.startTime = startTime;
       this.endTime = endTime;
       this.registerStartTime = registerStartTime;
       this.distributionTime = distributionTime;
       this.claimEndTime = claimEndTime;
       this.cancelEndTime = cancelEndTime;
       this.saleEndTime = saleEndTime;
       this.studentGroups = studentGroups;
       this.lotterySeats = lotterySeats;
       this.lotteryRegistrations = lotteryRegistrations;
    }
   
    public Integer getLotteryId() {
        return this.lotteryId;
    }
    
    public void setLotteryId(Integer lotteryId) {
        this.lotteryId = lotteryId;
    }
    public VenueInfo getVenueInfo() {
        return this.venueInfo;
    }
    
    public void setVenueInfo(VenueInfo venueInfo) {
        this.venueInfo = venueInfo;
    }
    public AdminInfo getAdminInfo() {
        return this.adminInfo;
    }
    
    public void setAdminInfo(AdminInfo adminInfo) {
        this.adminInfo = adminInfo;
    }
    public String getDisplayName() {
        return this.displayName;
    }
    
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
    public Date getRegisterStartTime() {
        return this.registerStartTime;
    }
    
    public void setRegisterStartTime(Date registerStartTime) {
        this.registerStartTime = registerStartTime;
    }
    public Date getDistributionTime() {
        return this.distributionTime;
    }
    
    public void setDistributionTime(Date distributionTime) {
        this.distributionTime = distributionTime;
    }
    public Date getClaimEndTime() {
        return this.claimEndTime;
    }
    
    public void setClaimEndTime(Date claimEndTime) {
        this.claimEndTime = claimEndTime;
    }
    public Date getCancelEndTime() {
        return this.cancelEndTime;
    }
    
    public void setCancelEndTime(Date cancelEndTime) {
        this.cancelEndTime = cancelEndTime;
    }
    public Date getSaleEndTime() {
        return this.saleEndTime;
    }
    
    public void setSaleEndTime(Date saleEndTime) {
        this.saleEndTime = saleEndTime;
    }
    
    public Set getStudentGroups() {
        return this.studentGroups;
    }
    public void setStudentGroups(Set studentGroups) {
        this.studentGroups = studentGroups;
    }
    public void addStudentGroup(StudentGroup studentGroup) {
        studentGroup.setLotteryEvent(this);
        studentGroups.add(studentGroup);
    }

    public Set getLotterySeats() {
        return this.lotterySeats;
    }
    public void setLotterySeats(Set lotterySeats) {
        this.lotterySeats = lotterySeats;
    }
    public void addLotterySeat(LotterySeat lotterySeat) {
        lotterySeat.setLotteryEvent(this);
        lotterySeats.add(lotterySeat);
    }

    public Set getLotteryRegistrations() {
        return this.lotteryRegistrations;
    }
    public void setLotteryRegistrations(Set lotteryRegistrations) {
        this.lotteryRegistrations = lotteryRegistrations;
    }
    public void addLotteryRegistration(LotteryRegistration lotteryRegistration) {
        lotteryRegistration.setLotteryEvent(this);
        lotteryRegistrations.add(lotteryRegistration);
    }




}


