package lotto.model;
// Generated Dec 5, 2009 7:37:40 PM by Hibernate Tools 3.2.1.GA



/**
 * LotteryRegistrationId generated by hbm2java
 */
public class LotteryRegistrationId  implements java.io.Serializable {


     private int studentId;
     private int lotteryId;

    public LotteryRegistrationId() {
    }

    public LotteryRegistrationId(int studentId, int lotteryId) {
       this.studentId = studentId;
       this.lotteryId = lotteryId;
    }
   
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }
    public int getLotteryId() {
        return this.lotteryId;
    }
    
    public void setLotteryId(int lotteryId) {
        this.lotteryId = lotteryId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LotteryRegistrationId) ) return false;
		 LotteryRegistrationId castOther = ( LotteryRegistrationId ) other; 
         
		 return (this.getStudentId()==castOther.getStudentId())
 && (this.getLotteryId()==castOther.getLotteryId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getStudentId();
         result = 37 * result + this.getLotteryId();
         return result;
   }   


}


