package lotto.model;
// Generated Dec 5, 2009 7:37:40 PM by Hibernate Tools 3.2.1.GA



/**
 * LotterySeatId generated by hbm2java
 */
public class LotterySeatId  implements java.io.Serializable {


     private int lotteryId;
     private int section;
     private int row;
     private int seatNo;

    public LotterySeatId() {
    }

    public LotterySeatId(int lotteryId, int section, int row, int seatNo) {
       this.lotteryId = lotteryId;
       this.section = section;
       this.row = row;
       this.seatNo = seatNo;
    }
   
    public int getLotteryId() {
        return this.lotteryId;
    }
    
    public void setLotteryId(int lotteryId) {
        this.lotteryId = lotteryId;
    }
    public int getSection() {
        return this.section;
    }
    
    public void setSection(int section) {
        this.section = section;
    }
    public int getRow() {
        return this.row;
    }
    
    public void setRow(int row) {
        this.row = row;
    }
    public int getSeatNo() {
        return this.seatNo;
    }
    
    public void setSeatNo(int seatNo) {
        this.seatNo = seatNo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof LotterySeatId) ) return false;
		 LotterySeatId castOther = ( LotterySeatId ) other; 
         
		 return (this.getLotteryId()==castOther.getLotteryId())
 && (this.getSection()==castOther.getSection())
 && (this.getRow()==castOther.getRow())
 && (this.getSeatNo()==castOther.getSeatNo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getLotteryId();
         result = 37 * result + this.getSection();
         result = 37 * result + this.getRow();
         result = 37 * result + this.getSeatNo();
         return result;
   }   


}


