package lotto.model;
// Generated Dec 5, 2009 7:37:40 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * MailingAddress generated by hbm2java
 */
public class MailingAddress  implements java.io.Serializable {


     private Integer addrId;
     private String line1;
     private String line2;
     private String city;
     private String state;
     private String zip;
     private String country;
     private String homePhone;
     private String mobilePhone;
     private Set adminInfos = new HashSet(0);
     private Set studentInfosForCurrentAddr = new HashSet(0);
     private Set studentInfosForPermanentAddr = new HashSet(0);
     private Set studentInfosForInternationalAddr = new HashSet(0);

    public MailingAddress() {
    }

    public MailingAddress(String line1, String line2, String city, String state, String zip, String country, String homePhone, String mobilePhone, Set adminInfos, Set studentInfosForCurrentAddr, Set studentInfosForPermanentAddr, Set studentInfosForInternationalAddr) {
       this.line1 = line1;
       this.line2 = line2;
       this.city = city;
       this.state = state;
       this.zip = zip;
       this.country = country;
       this.homePhone = homePhone;
       this.mobilePhone = mobilePhone;
       this.adminInfos = adminInfos;
       this.studentInfosForCurrentAddr = studentInfosForCurrentAddr;
       this.studentInfosForPermanentAddr = studentInfosForPermanentAddr;
       this.studentInfosForInternationalAddr = studentInfosForInternationalAddr;
    }
   
    public Integer getAddrId() {
        return this.addrId;
    }
    
    public void setAddrId(Integer addrId) {
        this.addrId = addrId;
    }
    public String getLine1() {
        return this.line1;
    }
    
    public void setLine1(String line1) {
        this.line1 = line1;
    }
    public String getLine2() {
        return this.line2;
    }
    
    public void setLine2(String line2) {
        this.line2 = line2;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public String getZip() {
        return this.zip;
    }
    
    public void setZip(String zip) {
        this.zip = zip;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getHomePhone() {
        return this.homePhone;
    }
    
    public void setHomePhone(String homePhone) {
        this.homePhone = homePhone;
    }
    public String getMobilePhone() {
        return this.mobilePhone;
    }
    
    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }
    public Set getAdminInfos() {
        return this.adminInfos;
    }
    
    public void setAdminInfos(Set adminInfos) {
        this.adminInfos = adminInfos;
    }
    public Set getStudentInfosForCurrentAddr() {
        return this.studentInfosForCurrentAddr;
    }
    
    public void setStudentInfosForCurrentAddr(Set studentInfosForCurrentAddr) {
        this.studentInfosForCurrentAddr = studentInfosForCurrentAddr;
    }
    public Set getStudentInfosForPermanentAddr() {
        return this.studentInfosForPermanentAddr;
    }
    
    public void setStudentInfosForPermanentAddr(Set studentInfosForPermanentAddr) {
        this.studentInfosForPermanentAddr = studentInfosForPermanentAddr;
    }
    public Set getStudentInfosForInternationalAddr() {
        return this.studentInfosForInternationalAddr;
    }
    
    public void setStudentInfosForInternationalAddr(Set studentInfosForInternationalAddr) {
        this.studentInfosForInternationalAddr = studentInfosForInternationalAddr;
    }




}


