package lotto.model;
// Generated Dec 5, 2009 7:37:40 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * StudentInfo generated by hbm2java
 */
public class StudentInfo  implements java.io.Serializable {


     private int studentId;
     private MailingAddress mailingAddressByCurrentAddr;
     private MailingAddress mailingAddressByInternationalAddr;
     private MailingAddress mailingAddressByPermanentAddr;
     private String username;
     private String password;
     private short active;
     private String name;
     private String email;
     private Date birthday;
     private Date dateEnrolled;
     private Date expectedGradDate;
     private String college;
     private String degree;
     private String degreeType;
     private Double loyaltyWeight;
     private Set studentGroups = new HashSet(0);
     private Set lotteryRegistrations = new HashSet(0);
     private Set lotterySeats = new HashSet(0);

    public StudentInfo() {
    }

	
    public StudentInfo(int studentId, String username, String password, short active, String name, String email) {
        this.studentId = studentId;
        this.username = username;
        this.password = password;
        this.active = active;
        this.name = name;
        this.email = email;
    }
    public StudentInfo(int studentId, MailingAddress mailingAddressByCurrentAddr, MailingAddress mailingAddressByInternationalAddr, MailingAddress mailingAddressByPermanentAddr, String username, String password, short active, String name, String email, Date birthday, Date dateEnrolled, Date expectedGradDate, String college, String degree, String degreeType, Double loyaltyWeight, Set studentGroups, Set lotteryRegistrations, Set lotterySeats) {
       this.studentId = studentId;
       this.mailingAddressByCurrentAddr = mailingAddressByCurrentAddr;
       this.mailingAddressByInternationalAddr = mailingAddressByInternationalAddr;
       this.mailingAddressByPermanentAddr = mailingAddressByPermanentAddr;
       this.username = username;
       this.password = password;
       this.active = active;
       this.name = name;
       this.email = email;
       this.birthday = birthday;
       this.dateEnrolled = dateEnrolled;
       this.expectedGradDate = expectedGradDate;
       this.college = college;
       this.degree = degree;
       this.degreeType = degreeType;
       this.loyaltyWeight = loyaltyWeight;
       this.studentGroups = studentGroups;
       this.lotteryRegistrations = lotteryRegistrations;
       this.lotterySeats = lotterySeats;
    }
   
    public int getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(int studentId) {
        this.studentId = studentId;
    }
    public MailingAddress getMailingAddressByCurrentAddr() {
        return this.mailingAddressByCurrentAddr;
    }
    
    public void setMailingAddressByCurrentAddr(MailingAddress mailingAddressByCurrentAddr) {
        this.mailingAddressByCurrentAddr = mailingAddressByCurrentAddr;
    }
    public MailingAddress getMailingAddressByInternationalAddr() {
        return this.mailingAddressByInternationalAddr;
    }
    
    public void setMailingAddressByInternationalAddr(MailingAddress mailingAddressByInternationalAddr) {
        this.mailingAddressByInternationalAddr = mailingAddressByInternationalAddr;
    }
    public MailingAddress getMailingAddressByPermanentAddr() {
        return this.mailingAddressByPermanentAddr;
    }
    
    public void setMailingAddressByPermanentAddr(MailingAddress mailingAddressByPermanentAddr) {
        this.mailingAddressByPermanentAddr = mailingAddressByPermanentAddr;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public short getActive() {
        return this.active;
    }
    
    public void setActive(short active) {
        this.active = active;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public Date getDateEnrolled() {
        return this.dateEnrolled;
    }
    
    public void setDateEnrolled(Date dateEnrolled) {
        this.dateEnrolled = dateEnrolled;
    }
    public Date getExpectedGradDate() {
        return this.expectedGradDate;
    }
    
    public void setExpectedGradDate(Date expectedGradDate) {
        this.expectedGradDate = expectedGradDate;
    }
    public String getCollege() {
        return this.college;
    }
    
    public void setCollege(String college) {
        this.college = college;
    }
    public String getDegree() {
        return this.degree;
    }
    
    public void setDegree(String degree) {
        this.degree = degree;
    }
    public String getDegreeType() {
        return this.degreeType;
    }
    
    public void setDegreeType(String degreeType) {
        this.degreeType = degreeType;
    }
    public Double getLoyaltyWeight() {
        return this.loyaltyWeight;
    }
    public void setLoyaltyWeight(Double loyaltyWeight) {
        this.loyaltyWeight = loyaltyWeight;
    }

    public Set getStudentGroups() {
        return this.studentGroups;
    }
    public void setStudentGroups(Set studentGroups) {
        this.studentGroups = studentGroups;
    }
    public void addStudentGroup(StudentGroup studentGroup) {
        studentGroup.setStudentInfo(this);
        studentGroups.add(studentGroup);
    }

    public Set getLotteryRegistrations() {
        return this.lotteryRegistrations;
    }
    public void setLotteryRegistrations(Set lotteryRegistrations) {
        this.lotteryRegistrations = lotteryRegistrations;
    }
    public void addLotteryRegistration(LotteryRegistration lotteryRegistration) {
        lotteryRegistration.setStudentInfo(this);
        lotteryRegistrations.add(lotteryRegistration);
    }

    public Set getLotterySeats() {
        return this.lotterySeats;
    }
    public void setLotterySeats(Set lotterySeats) {
        this.lotterySeats = lotterySeats;
    }
    public void addLotterySeat(LotterySeat lotterySeat) {
        lotterySeat.setStudentInfo(this);
        lotterySeats.add(lotterySeat);
    }



}


