package lotto.model;
// Generated Dec 5, 2009 7:37:40 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * StudentGroup generated by hbm2java
 */
public class StudentGroup  implements java.io.Serializable {


     private Integer groupId;
     private LotteryEvent lotteryEvent;
     private StudentInfo studentInfo;
     private String name;
     private Set lotterySeats = new HashSet(0);
     private Set lotteryRegistrations = new HashSet(0);

    public StudentGroup() {
    }

	
    public StudentGroup(LotteryEvent lotteryEvent, StudentInfo studentInfo, String name) {
        this.lotteryEvent = lotteryEvent;
        this.studentInfo = studentInfo;
        this.name = name;
    }
    public StudentGroup(LotteryEvent lotteryEvent, StudentInfo studentInfo, String name, Set lotterySeats, Set lotteryRegistrations) {
       this.lotteryEvent = lotteryEvent;
       this.studentInfo = studentInfo;
       this.name = name;
       this.lotterySeats = lotterySeats;
       this.lotteryRegistrations = lotteryRegistrations;
    }
   
    public Integer getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }
    public LotteryEvent getLotteryEvent() {
        return this.lotteryEvent;
    }
    
    public void setLotteryEvent(LotteryEvent lotteryEvent) {
        this.lotteryEvent = lotteryEvent;
    }
    public StudentInfo getStudentInfo() {
        return this.studentInfo;
    }
    
    public void setStudentInfo(StudentInfo studentInfo) {
        this.studentInfo = studentInfo;
    }
    public String getName() {
        return this.name;
    }
    public void setName(String name) {
        this.name = name;
    }

    public Set getLotterySeats() {
        return this.lotterySeats;
    }
    public void setLotterySeats(Set lotterySeats) {
        this.lotterySeats = lotterySeats;
    }
    public void addLotterySeat(LotterySeat lotterySeat) {
        lotterySeat.setStudentGroup(this);
        lotterySeats.add(lotterySeat);
    }

    public Set getLotteryRegistrations() {
        return this.lotteryRegistrations;
    }
    public void setLotteryRegistrations(Set lotteryRegistrations) {
        this.lotteryRegistrations = lotteryRegistrations;
    }
    public void addLotteryRegistration(LotteryRegistration lotteryRegistration) {
        lotteryRegistration.setStudentGroup(this);
        lotteryRegistrations.add(lotteryRegistration);
    }




}


