package lotto.model;
// Generated Dec 5, 2009 7:37:40 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * VenueSection generated by hbm2java
 */
public class VenueSection  implements java.io.Serializable {


     private Integer sectionId;
     private VenueInfo venueInfo;
     private String label;
     private String location;
     private Integer position;
     private Set venueRows = new HashSet(0);

    public VenueSection() {
    }

	
    public VenueSection(VenueInfo venueInfo, String label) {
        this.venueInfo = venueInfo;
        this.label = label;
    }
    public VenueSection(VenueInfo venueInfo, String label, String location, Integer position, Set venueRows) {
       this.venueInfo = venueInfo;
       this.label = label;
       this.location = location;
       this.position = position;
       this.venueRows = venueRows;
    }
   
    public Integer getSectionId() {
        return this.sectionId;
    }
    
    public void setSectionId(Integer sectionId) {
        this.sectionId = sectionId;
    }
    public VenueInfo getVenueInfo() {
        return this.venueInfo;
    }
    
    public void setVenueInfo(VenueInfo venueInfo) {
        this.venueInfo = venueInfo;
    }
    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public Integer getPosition() {
        return this.position;
    }
    
    public void setPosition(Integer position) {
        this.position = position;
    }
    public Set getVenueRows() {
        return this.venueRows;
    }
    
    public void setVenueRows(Set venueRows) {
        this.venueRows = venueRows;
    }
    public void addVenueRow(VenueRow venueRow) {
        venueRow.setVenueSection(this);
        venueRows.add(venueRow);
    }



}


