package lotto.model;
// Generated Dec 5, 2009 7:37:40 PM by Hibernate Tools 3.2.1.GA



/**
 * VenueSeatId generated by hbm2java
 */
public class VenueSeatId  implements java.io.Serializable {


     private int sectionId;
     private int row;
     private int seatNo;

    public VenueSeatId() {
    }

    public VenueSeatId(int sectionId, int row, int seatNo) {
       this.sectionId = sectionId;
       this.row = row;
       this.seatNo = seatNo;
    }
   
    public int getSectionId() {
        return this.sectionId;
    }
    
    public void setSectionId(int sectionId) {
        this.sectionId = sectionId;
    }
    public int getRow() {
        return this.row;
    }
    
    public void setRow(int row) {
        this.row = row;
    }
    public int getSeatNo() {
        return this.seatNo;
    }
    
    public void setSeatNo(int seatNo) {
        this.seatNo = seatNo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VenueSeatId) ) return false;
		 VenueSeatId castOther = ( VenueSeatId ) other; 
         
		 return (this.getSectionId()==castOther.getSectionId())
 && (this.getRow()==castOther.getRow())
 && (this.getSeatNo()==castOther.getSeatNo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getSectionId();
         result = 37 * result + this.getRow();
         result = 37 * result + this.getSeatNo();
         return result;
   }   


}


