package lotto.model;
// Generated Dec 5, 2009 7:37:40 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * VenueRow generated by hbm2java
 */
public class VenueRow  implements java.io.Serializable {


     private VenueRowId id;
     private VenueSection venueSection;
     private String label;
     private Integer position;
     private Set venueSeats = new HashSet(0);

    public VenueRow() {
    }

	
    public VenueRow(VenueRowId id, VenueSection venueSection, String label) {
        this.id = id;
        this.venueSection = venueSection;
        this.label = label;
    }
    public VenueRow(VenueRowId id, VenueSection venueSection, String label, Integer position, Set venueSeats) {
       this.id = id;
       this.venueSection = venueSection;
       this.label = label;
       this.position = position;
       this.venueSeats = venueSeats;
    }
   
    public VenueRowId getId() {
        return this.id;
    }
    
    public void setId(VenueRowId id) {
        this.id = id;
    }
    public VenueSection getVenueSection() {
        return this.venueSection;
    }
    
    public void setVenueSection(VenueSection venueSection) {
        this.venueSection = venueSection;
    }
    public String getLabel() {
        return this.label;
    }
    
    public void setLabel(String label) {
        this.label = label;
    }
    public Integer getPosition() {
        return this.position;
    }
    
    public void setPosition(Integer position) {
        this.position = position;
    }
    public Set getVenueSeats() {
        return this.venueSeats;
    }
    
    public void setVenueSeats(Set venueSeats) {
        this.venueSeats = venueSeats;
    }
    public void addVenueSeat(VenueSeat venueSeat) {
        venueSeat.setVenueRow(this);
        venueSeats.add(venueSeat);
    }



}


